<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\MethodNotAllowedHttpException;

use kartik\form\ActiveForm;

class BaseHomeController extends Controller
{

    public $pageTitle = '';
    public $userNotify = [];
    public $userMessage = [];
    public $userTask = [];

    public function behaviors()
    {
        return [
            'access' => [
                'class'        => AccessControl::className(),
                'rules'        => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['error'],
                        'allow'   => true,
                    ],
                    [
                        'actions' => ['login'],
                        'allow'   => true,
                        'roles'   => ['?'],
                    ],
                ],
                'denyCallback' => function ($rules, $action) {
                    Yii::$app->user->returnUrl = Yii::$app->request->url;
                    return $this->redirect(['site/login']);
                },
            ],
        ];
    }

    /**
     * 初始化
     */
    public function init()
    {
        Yii::$container->set('yii\widgets\LinkPager', [
            'firstPageLabel'   => '首页',
            'lastPageLabel'    => '尾页',
            'prevPageLabel'    => '上页',
            'nextPageLabel'    => '下页',
            'hideOnSinglePage' => false,
            'options'          => [
                'class' => 'pagination pull-right'
            ],
        ]);

        Yii::$container->set('yii\data\Pagination', [
            'defaultPageSize' => 15
        ]);
        Yii::$container->set('yii\grid\ActionColumn', [
            'template' => '{update} {delete}',
        ]);
        Yii::$container->set(ActiveForm::className(), [
            'type' => ActiveForm::TYPE_HORIZONTAL,
        ]);
        Yii::$container->set('yii\captcha\Captcha', [
            'captchaAction' => 'home/captcha'
        ]);
        Yii::$container->set('yii\captcha\CaptchaValidator', [
            'captchaAction' => 'home/captcha'
        ]);
        Yii::$container->set('frontend\behaviors\TestBehavior', [
            'msg' => 'xxxxxxx',
        ]);
    }

    /**
     * 强制刷新菜单
     * @return \yii\web\Response
     */
    public function actionReflushmenu()
    {
        Yii::$app->session->setFlash('reflush');
        return $this->goHome();
    }

    public function beforeAction($action)
    {
        parent::beforeAction($action);
        $this->layout = 'homeLayout';

        return true;
    }

    public function render($view, $params = [])
    {
        /** 指定标题 */
        if($this->pageTitle)
        {
            Yii::$app->view->params['pageTitle'] = $this->pageTitle;
        }

        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        parent::afterAction($action, $result);

        return $result;
    }
}
